### ISSUE TITLE
Tentative ChatGPT help-desk workshop: people recommendations

### ISSUE THREAD

**Issue by cjandrew** [uio-mana/Helpdesk#8]
Hi all,

Yesterday at the GEco retreat, @ErikKusch, @rukayaj  & @MichalTorma (+ GEco'ers) discussed a possible workshop topic on using ChatGPT (i.e., the syntax / language / tricks that help).

I am following up here with some other people you may or may not want to reach out to about including -- I saw their presentations last month and they, similarly, discussed techniques for optimizing information asked from ChatGPT:

1) [Verónica Expósito Mäki-Marttunen](https://www.med.uio.no/norment/personer/postdoktorer/makimarttunen/index.html) held a "[Basics of ChatGPT4 coder interpreter](https://www.ub.uio.no/english/courses-events/events/dsc/2024/digital-scholarship-days/14-chatgpt4.html)". The workshop was more about using the data analysis tool (also possibly a relevant workshop topic), with tips / tricks she mentioned as a side component.

2) From a "[REAL undervisning - Kunstig intelligens i undervisning og læring](https://www.mn.uio.no/kurt/aktuelt/arrangementer/2024/real-undervisning-.html)", quite a few people discussed ChatGPT. Perhaps the most relevant would be the last two people, hesitantly I write, but you can see their presentations and decide. 

Carrie

**Comment by rukayaj** [comment]
Thanks Carrie!

**Comment by rukayaj** [comment]
Week of May 27th - 31st is good for me, the other one not so much except for the 13th & 14th.

**Comment by rukayaj** [comment]
Abstract: 
In this seminar, we'll explore practical ways to use large language models such as ChatGPT to boost problem-solving and learning. We'll show how these tools can aid in research, simplify and speed up data analysis, and enhance teaching methods. By integrating language models into your work, you can get an intelligent editor, pair-programmer and critical sounding board to bounce ideas off. They are particularly powerful as a learning tool. Our goal is to have a group discussion and talk about the different strategies with these tools that work for us .

**Comment by ErikKusch** [comment]
Organised with #9
